server:
  port: 8800

mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.slf4j.Slf4jImpl

spring:
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/oh-my-oa?serverTimezone=GMT%2B8&userSSL=false&characterEncoding=utf-8
    username: root
    password: mingge123
  jackson:
    time-zone: GMT+8
    date-format: yyyy-MM-dd HH:mm:ss
  redis:
    host: 101.43.107.164
    port: 6380
    database: 0
    timeout: 1800000
    password: wzm123
    lettuce:
      pool:
        max-active: 20 # 最大连接数
        max-wait: -1 # 最大阻塞等待时间（负数表示没限制）
        max-idle: 5 # 最大空闲
        min-idle: 0 # 最小空闲
