server:
  port: 8800

mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.slf4j.Slf4jImpl

spring:
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/oh-my-oa?serverTimezone=GMT%2B8&userSSL=false&characterEncoding=utf-8
    username: root
    password: mingge123
  jackson:
    time-zone: GMT+8
    date-format: yyyy-MM-dd HH:mm:ss
